### ISSUE TITLE
componentDidUnmount() does not exist

### ISSUE THREAD

**Issue by whitphx** [jxnblk/rgx#10]
Hello, 
When I use this library, a following message is shown:

```
Warning: Grid has a method called componentDidUnmount(). But there is no such lifecycle method. Did you mean componentWillUnmount()?
```

It seems that this wrong method name was fixed at 6ef6f08d9ff09304751e23bff4cef818c2ff9d61 in `src/Grid.jsx` but it remains in `component/Grid.js`

I wonder how to build src to component and cannot fix it.
Could you modify it?

**Comment by jxnblk** [comment]
Did you install from npm? The prepublish script should compile it, but I might've forgotten to publish the patch

**Comment by whitphx** [comment]
Yes, I did from npm.

**Comment by jxnblk** [comment]
I updated the build scripts and from what I can tell that change should be published in the latest patch. Let me know if you're still having issues.

**Comment by whitphx** [comment]
Thank you.
