### ISSUE TITLE
"overflow: hidden" on Grid/Row can cause problem with absolute positioned elements

### ISSUE THREAD

**Issue by elverskog** [jxnblk/rgx#6]
Hi - Just curious what the reason was for the Grid element having "overflow: hidden"? I was using your module for a form and was using an absolutely positioned custom select-type field (drop down) in a Grid. Which of course got cut off. I commented out that overflow line for now but am concerned what ill affects it may cause down the line.

Interesting approach btw - was using Jeet before the switch to inline styles. Curious to see how your module can be used when doing fine grained device tuning (or if it obviates it).

**Comment by jxnblk** [comment]
The `overflow: hidden` is to compensate for the negative margins and prevent horizontal scrolling. I'm not sure that removing that style for the sake of positioned elements is the best idea, but let me think about solutions.

**Comment by elverskog** [comment]
Thanks. Would it be possible to do something like Jeet (http://jeet.gs/) that doesn't use the left/right negative margin solution. This would obviate the need for the overflow: hidden. Of course, since you don't have access the CSS pseudo classes you would have to check for first or last with JS.

**Comment by jxnblk** [comment]
Actually could just change it to overflow-x hidden – that would work in your case, right?

**Comment by elverskog** [comment]
I don't think so. As one of the custom select list may need to go outside the row either left or right.
